//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//
//

import AWSCore


// Name of Hangman bot
let HangmanBotName = "Hangman"
// Alias for Hangman bot
let HangmanBotAlias = "$LATEST"
// Region for Hangman bot
let HangmanBotRegion: AWSRegionType = .USEast1
